general:
  artifacts:
    - "./tests/screenshots" #Save the screenshots for the tests
 
dependencies:
  pre:
    - sudo pip install -U selenium	
 
test:
   override:
    - python tests/Navigate_Qxf2_Tutorial_Test.py
