
version: 2
jobs:
  build:
    docker:
      
      - image: circleci/python:3.6.1

     

    working_directory: ~/tmp

    steps:
      - checkout
      
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run: python Launch.py 
          
      - store_artifacts:
          path: test-reports
          destination: test-reports