version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers


    steps:
      - checkout

      - run:
          name: Install requests
          command: |
            sudo pip install -r requirement.txt


      - run:
          name: Run Selenium test
          command: |
            python -m pytest tests/Launch.py

      - store_artifacts:
          path: ./screenshots
          destination: screenshots-file
      - store_artifacts:
          path: ./log
          destination: logs-file

          

